(define-key evil-normal-state-map (kbd "C-u") 'evil-scroll-up)
(load-theme 'wombat)
(cl-loop for (mode . state) in '((inferior-emacs-lisp-mode . emacs)
                                 (ag-mode . emacs)
                                 (fundamental-mode . emacs)
                                 (nav-mode . emacs)
                                 (pylookup-mode . emacs)
                                 ;; CIDER modes
                                 (cider-docview-mode . emacs)
                                 (cider-inspector-mode . emacs)
                                 (cider-macroexpansion-mode . emacs)
                                 (cider-repl-mode . emacs)
                                 (cider-result-mode . emacs)
                                 (cider-stacktrace-mode . emacs)
                                 (cider-test-report-mode . emacs)

                                 (comint-mode . emacs)
                                 (ebib-entry-mode . emacs)
                                 (ebib-index-mode . emacs)
                                 (ebib-log-mode . emacs)
                                 (eshell-mode . emacs)
                                 (elfeed-show-mode . emacs)
                                 (elfeed-search-mode . emacs)
                                 (ensime-inf-mode . emacs)
                                 (gtags-select-mode . emacs)
                                 (git-commit-mode . emacs)
                                 (git-rebase-mode . emacs)
                                 (dired-mode . emacs)
                                 (shell-mode . emacs)
                                 (term-mode . emacs)
                                 (bc-menu-mode . emacs)
                                 (magit-status-mode . emacs)
                                 (magit-branch-manager-mode . emacs)
                                 (semantic-symref-results-mode . emacs)
                                 (rdictcc-buffer-mode . emacs)
                                 (erc-mode . normal))
         do (evil-set-initial-state mode state))

;; Window switching
(define-key evil-normal-state-map (kbd "C-l") 'windmove-right)
(define-key evil-normal-state-map (kbd "C-h") 'windmove-left)
(define-key evil-normal-state-map (kbd "C-j") 'windmove-down)
(define-key evil-normal-state-map (kbd "C-k") 'windmove-up)
(define-key evil-normal-state-map (kbd "C-p") 'helm-projectile)
(define-key evil-normal-state-map (kbd "C-b") 'helm-buffers-list)

(define-key evil-normal-state-map ",n" 'neotree-toggle)
(define-key evil-normal-state-map ",m" 'neotree-find)

(define-key evil-normal-state-map [escape] 'keyboard-quit)
(define-key evil-visual-state-map [escape] 'keyboard-quit)
(define-key minibuffer-local-map [escape] 'minibuffer-keyboard-quit)
(define-key minibuffer-local-ns-map [escape] 'minibuffer-keyboard-quit)
(define-key minibuffer-local-completion-map [escape] 'minibuffer-keyboard-quit)
(define-key minibuffer-local-must-match-map [escape] 'minibuffer-keyboard-quit)
(define-key minibuffer-local-isearch-map [escape] 'minibuffer-keyboard-quit)
(define-key helm-map (kbd "ESC") 'helm-keyboard-quit)

(scroll-bar-mode -1)
(global-set-key (kbd "C-p") 'helm-projectile)
(global-set-key (kbd "M-x") 'helm-M-x)
(global-set-key (kbd "C-b") 'helm-buffers-list)


(add-hook 'neotree-mode-hook
          (lambda ()
            (define-key evil-normal-state-local-map (kbd "TAB") 'neotree-enter)
            (define-key evil-normal-state-local-map (kbd "SPC") 'neotree-enter)
            (define-key evil-normal-state-local-map (kbd "q") 'neotree-hide)
            (define-key evil-normal-state-local-map (kbd "RET") 'neotree-enter)))


(defun my-move-key (keymap-from keymap-to key)
  "Moves key binding from one keymap to another, deleting from the old location. "
  (define-key keymap-to key (lookup-key keymap-from key))
  (define-key keymap-from key nil))
(my-move-key evil-motion-state-map evil-normal-state-map (kbd "RET"))
(my-move-key evil-motion-state-map evil-normal-state-map " ")
(my-move-key evil-motion-state-map evil-normal-state-map (kbd "C-b"))
